#Make sure that your server folder have "world" world!
#To regenerate your world after game you need to paste "map" world with clean map in your server folder!

#If you want, you can connect mysql to collect players stats
#jdbc:mysql://[host]:[port]/[database]
#Create [database] in your MySQL before loading!
MySQL:
  enabled: true
  url: "jdbc:mysql://localhost:3306/bedwars?useSSL=false&autoReConnect=true"
  user: "root"
  password: ""
#if BungeeCord enabled, player will be teleported at lobby at game end, else will be run command_at_game_end by player

BungeeCord:
  enabled: false
  lobby: "lobby"
command_at_game_end: "/lobby"

#TAB plugin by NEZNAMY - https://github.com/NEZNAMY/TAB/releases/tag/2.9.2
#With this plugin players will have colored nicknames in TAB
TAB_plugin_support: true

#PLUGIN CANNOT REGENERATE MAP!
#You need to use shell script to replace map at your server folder after restart!
#SHELL EXAMPLE of start.sh (linux)
#rm -R world
#cp -avr map world
#screen -S bw7 -X quit
#screen -S bw7 -m -d java -Xincgc -server -jar -Xms800m -Xmx800m spigot-1.17.1.jar
#
#SHELL EXAMPLE of start.bat (windows)
#rd /s /q "logs"
#rd /s /q "world"
#xcopy map world /D /E /C /R /H /I /K /Y
#java -jar -Xms600m -Xmx600m spigot-1.17.1.jar
#
#folder map should have CLEAN map

game_end_restart_seconds: 15
game_end_to_lobby_players_seconds: 12
command_stat_cooldown: 5 #seconds

fireball_cooldown: 20 #20 ticks = 1 second
fireball_radius_explosion: 3 #in blocks
fireball_distance_from_player: 1.0
disable_tnt_damage_others_players: true
glass_unexplosion: true #should glass save from tnt?
players_need_food: false

give_money: true #MAKE SURE that you have Vault plugin and ANY Economy plugin!
bed_break_money: 50
win_money: 100
final_kill_money: 25

respawn_time_seconds: 5
autodeath_y_coord: -70 #if player below this coord he auto die
height_limit: 255
border: 500
lobby_time: 30
game_time: 2400 #seconds
slow_and_blind_after_bed_break: true
sounds:
  bed_break:
    enabled: true
    sound: "ENTITY_ENDER_DRAGON_AMBIENT"

#These blocks u can place around ur bed to get some features
specific_blocks:
  distance_to_bed_need: 5
  bell: #ringing when opponents around ur bed
    enabled: true
    material: "ANVIL"
    sound: "BLOCK_ANVIL_PLACE"
  campfire: #disable ALL upgrades of ur opponents around ur bed
    enabled: true
    material: "ENCHANTMENT_TABLE"

upgrades:
  trap: 2 #in diamonds
  generator:
    2: 8
    3: 16
    4: 24
    5: 32
  sword:
    2: 8
    3: 16
    4: 24
  armor:
    2: 4
    3: 8
    4: 16
    5: 32
  speed:
    2: 4
    3: 8
    4: 16
up_tier_time:
  '2': 1600
  '3': 800
bed_gone_time: 400
iron_tier:
  '1':
    amount: 1
    time: 1
  '2':
    amount: 2
    time: 1
  '3':
    amount: 2
    time: 1
gold_tier:
  '1':
    amount: 1
    time: 4
  '2':
    amount: 1
    time: 2
  '3':
    amount: 1
    time: 1
diamond_tier:
  '1':
    amount: 1
    time: 30
  '2':
    amount: 1
    time: 20
  '3':
    amount: 1
    time: 10
emerald_tier:
  '1':
    amount: 1
    time: 60
  '2':
    amount: 1
    time: 40
  '3':
    amount: 1
    time: 20

shops:
  blocks: []
  armor: []
  swords: []
  potions: []
  useful: []
  tools: []
  bows: []
arena:
  status: "reload"
  upgrades: []
  shops: []